apiVersion: v1
description: Connect OpenFaaS functions to Kafka topics
name: kafka-connector
version: 0.1.0
sources:
- https://github.com/openfaas-incubator/kafka-connector
home: https://www.openfaas.com
icon: https://raw.githubusercontent.com/openfaas/media/master/OpenFaaS_logo_stacked_opaque.png
keywords:
- functions
- service
maintainers:
- name: alexellis
  email: alex@openfaas.com
- name: roncrivera
  email: roncrivera@gmail.com
