apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: {{ template "kafka.name" . }}
    component: kafka-broker
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
  - port: 9092
    name: kafka-port
    targetPort: 9092
    protocol: TCP
  selector:
    app: kafka
    component: kafka-broker
